name: Expenses control CI

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v1
      # setup jdk
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # run detekt
      - name: Run detekt
        run: ./gradlew detekt

      - name: Run some unit tests
        run: ./gradlew test --stacktrace

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: app/build/reports
        if: always()

  androidTest:
    runs-on: macOS-latest #Have to use mac os for HAXM hw acceleration. although it uses 10x more run minutes than ubuntu on GH actions
    steps:
      - uses: actions/checkout@v2

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace